---
services:
  api:
    build:
      context: .
    container_name: leap25-api
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=leapdev
      - DB_USER_PASSWORD=Dev123456
      - DB_NAME=leap25_db
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: leap25-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Dev123456
      - MYSQL_DATABASE=leap25_db
      - MYSQL_USER=leapdev
      - MYSQL_PASSWORD=Dev123456
    volumes:
      - mysql_data_leap25:/var/lib/mysql

volumes:
  mysql_data_leap25:

