---
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leap25-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=leap25db
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=leap25db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=secret
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: leap25-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leap25db
    volumes:
      - mysql-data-leap25:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data-leap25:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data-leap25:
  redis-data-leap25:
