---
name: Deploy Production

on:
  workflow_run:
    workflows: ["Continuous Delivery"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to K3s
        uses: steebchen/kubectl@v2
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: set image deployment/leap25-backend leap25-backend=ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
